#!/usr/bin/env python
import os, os.path as path
Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES=['USE_NO_EXPORT=1','NO_UNZIP=1'])
Env.Append(CPPPATH=[path.join(build.kroll_source_dir,'api')])
Env.Append(FRAMEWORKS=['Cocoa','IOKit'])
Env.Append(LIBS=['dl'])

sources = ['main.mm']
Env.Append(CPPPATH=[build.kroll_utils_dir])
sources += build.get_kroll_utils(path.join(build.dir, 'objs', 'boot'))

kboot_out = path.join(build.dir, 'runtime', 'template', 'kboot')
p = Env.Program(kboot_out, sources)
build.mark_build_target(p)
