#!/usr/bin/env python
Import('build')


OSX_SDK = '/Developer/SDKs/MacOSX10.4u.sdk'
OSX_UNIV_COMPILER = '-isysroot '+OSX_SDK+' -arch i386'
OSX_UNIV_LINKER = '-isysroot '+OSX_SDK+' -syslibroot,'+OSX_SDK

Env = build.env.Clone()
Env.Append(FRAMEWORKS=['Foundation','Cocoa'])
Env.Append(CCFLAGS=OSX_UNIV_COMPILER+' -x objective-c++')
Env.Append(LDFLAGS=OSX_UNIV_LINKER)
Env.Program(build.dir + '/kboot', ['boot.mm','../api/file_utils.cpp'])
