#!/usr/bin/env python
Import('build')
import os, os.path as path

Env = build.env.Clone()
Env.Append(LIBS=['dl'])

sources = ['main.cpp']

Env.Append(CPPPATH=[build.kroll_utils_dir])
sources += build.get_kroll_utils(path.join(build.dir, 'objs', 'boot'))

kboot_out = path.join(build.dir, 'runtime', 'template', 'kboot')
p = Env.Program(kboot_out, sources)
build.mark_build_target(p)
