#!/usr/bin/env python
Import('build')
import os, os.path as path

Env = build.env.Clone()
Env.Append(CPPPATH=[path.join(build.kroll_source_dir,'api')])
Env.Append(LIBS=['dl'])

fo = os.path.join(build.dir,'file_utils_boot.o')
o = Env.Object(target = fo, source = path.join(build.kroll_source_dir,'api','file_utils.cpp'))

sources = ['main.cpp', fo]
kboot_out = path.join(build.dir, 'runtime', 'template', 'kboot')
p = Env.Program(kboot_out, sources)
build.require(p)
