#!/usr/bin/env python
Import('build')
import os

modules = ['api', 'foo', 'python', 'foopy', 'javascript', 'foojs','ruby']

for module in modules:
	module_dir = build.dir + '/modules/' + module
	SConscript(module+'/SConscript', build_dir=module_dir, duplicate=0)
	out_dir = os.path.join(build.abstopdir,'modules',module)
	script = os.path.join(build.abstopdir,'build','module.py')
	os.system(script+' '+build.dir+' '+out_dir+' '+build.os)
	
	