#!/usr/bin/env python
Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES=('KROLL_HOST_EXPORT',1))
Env.Append(CPPPATH=['#common/win32','#common'])
Env.Append(CCFLAGS=['/DUNICODE'])
Env.Append(CCFLAGS=['/D_UNICODE'])
build.add_thirdparty(Env, 'poco')

t = Env.SharedLibrary(build.dir + '/runtime/khost', 
	Glob('*.cpp'),
	LIBS=['kroll','kernel32','shell32','user32','ole32','comctl32'])
build.mark_build_target(t)
