#!/usr/bin/env python
Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES=('KROLL_HOST_EXPORT',1))
Env.Append(CPPPATH=['#common/win32','#common'])
build.add_thirdparty(Env, 'poco')

Env.SharedLibrary(build.dir + '/runtime/khost', ['host.cpp','win32_job.cpp'], LIBS=['kroll','kernel32','shell32','user32','ole32','comctl32'])
Env.SharedLibrary(build.dir + '/khost', ['host.obj','win32_job.obj'], LIBS=['kroll','kernel32','shell32','user32','ole32','comctl32'])
