#!/usr/bin/env python
Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES={'KROLL_HOST_EXPORT':1})
Env.Append(CPPPATH=['#common/win32','#common'])
Env.SharedLibrary(build.dir + '/khost', ['host.cpp'], LIBS=['kroll','kernel32','shell32','user32','ole32','comctl32'])
