#!/usr/bin/env python
Import('build')

Env = build.env.Clone()
build.add_thirdparty(Env, 'poco')

if build.is_osx():
	Env.Append(LIBS=['kroll'])

Env.SharedLibrary(build.dir + '/foomodule', Glob('*.cpp'))
