#!/usr/bin/env python
import os
Import('build')

Env = build.env.Clone()

if build.is_osx():
   OSX_SDK = '/Developer/SDKs/MacOSX10.4u.sdk'
   OSX_UNIV_COMPILER = '-isysroot '+OSX_SDK+' -arch ppc -arch i386'
   OSX_UNIV_LINKER = '-isysroot '+OSX_SDK+' -syslibroot,'+OSX_SDK
   Env.Append(CCFLAGS=['-x', 'objective-c++'])
   Env.Append(FRAMEWORKS=['Cocoa'])
   Env.Append(CCFLAGS=OSX_UNIV_COMPILER)
   Env.Append(LDFLAGS=OSX_UNIV_LINKER)


if build.is_win32():
	Env.Append(LIBS=['user32','ole32'])

if build.is_linux():
	#if os.environ.has_key('PKG_CONFIG_PATH'):
		#Env.AppendENVPath('PKG_CONFIG_PATH', os.environ['PKG_CONFIG_PATH'])
	Env.ParseConfig('pkg-config --cflags --libs gtk+-2.0 gdk-2.0')

Env.Append(CPPPATH=['#host/'+ build.os, '#.'])
Env.Append(LIBS=['kroll','host'])
if build.is_osx() or build.is_linux():
	Env.Append(LIBS=['dl'])

p = Env.Program(build.dir + '/kernel', ['main.cpp'])
