#!/usr/bin/env python
import os, os.path as path

Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES={'WIN32_LEAN_AND_MEAN': 1})
Env.Append(CPPPATH=['#common/win32'])
Env.Append(LIBS = ['user32', 'shell32'])

p = Env.Program(build.dir + '/kinstall', ['installer.cpp', '../api/file_utils.obj', '../api/unzip/unzip.obj'])

command = 'mt.exe -nologo -manifest "%s/kinstall.exe.manifest" -outputresource:%s/kinstall.exe'
command = command % (build.dir, build.dir)

Env.AddPostAction(p, command)
