#!/usr/bin/env python
Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES={'WIN32_LEAN_AND_MEAN': 1})
Env.Append(CPPPATH=['#common/win32'])
Env.Program(build.dir + '/install', ['installer.cpp', 'unzip.cpp', '#common/win32/common.obj'], LIBS=['user32', 'shell32'])
