#!/usr/bin/env python
import os, os.path as path

Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES={'WIN32_LEAN_AND_MEAN': 1, 'NO_UNZIP' : 1})
Env.Append(CPPPATH=['#common/win32','#common'])
Env.Append(LIBS = ['shell32', 'user32'])

o = Env.Object(target = 'file_utils_boot.o', source = '../api/file_utils.cpp')
p = Env.Program(build.dir + '/kboot', ['boot.cpp','file_utils_boot.o'])

Env.AddPostAction(p, 'mt.exe -nologo -manifest "'+build.dir+'/kboot.exe.manifest'+'" -outputresource:'+build.absdir+'/kboot.exe')
