#!/usr/bin/env python
import os, os.path as path

Import('build')

Env = build.env.Clone()
Env.Append(CPPPATH = ['#.'])
Env.Append(CPPDEFINES=('KROLL_API_API_EXPORT', 1))
build.add_thirdparty(Env, 'poco')
    
Env.SharedLibrary(build.dir + '/apimodule', Glob('*.cpp'))
