#!/usr/bin/env python
import os, os.path as path

Import('build')

Env = build.env.Clone()
Env.Append(CPPPATH = ['#.'])
Env.Append(CPPDEFINES=('KROLL_API_API_EXPORT', 1))

build.add_thirdparty(Env, 'poco')

if build.is_osx() or build.is_win32():
	Env.Append(LIBS=['kroll'])

m = build.add_module('api', '0.1')
Env.SharedLibrary(m.build_dir + '/apimodule', Glob('*.cpp'))
Env.SharedLibrary(build.dir + '/apimodule', Glob('*.cpp'))
