#!/usr/bin/env python
from os import path
Import('build env module')

env.Append(CPPDEFINES=('KROLL_API_API_EXPORT', 1))

build.add_thirdparty(env, 'poco')
build.mark_build_target(env.SharedLibrary(
	path.join(module.dir, 'apimodule'), Glob('*.cpp')))
