#!/usr/bin/env python
Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES={'KROLL_HOST_EXPORT':1})
Env.Append(CCFLAGS=['-x', 'objective-c++'])
Env.Append(FRAMEWORKS=['Foundation', 'Cocoa'])
Env.SharedLibrary(build.dir + '/host', ['host.cpp', 'log.cpp'], LIBS=['kroll'])
