#!/usr/bin/env python
import os, os.path as path

Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES={'KROLL_HOST_EXPORT':1})
Env.Append(FRAMEWORKS=['Cocoa'])
build.add_thirdparty(Env, 'poco')

Env.Append(LIBS=['kroll'])

Env.SharedLibrary(build.dir + '/khost', ['host.cpp', 'log.cpp'])
